/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alquiler.de.autos;

import java.io.File;
import java.sql.Connection;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author yc
 */
public class reservar extends javax.swing.JFrame {
    Conexion con1 = new Conexion();
    Connection conet;
    /**
    /**
     * Creates new form reservar
     */
    private int id_alquiler;
    
    public reservar(int id_alquiler) {
        this.id_alquiler = id_alquiler;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre_cliente = new javax.swing.JTextField();
        apellidos_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        telefono_cliente = new javax.swing.JTextField();
        ine = new javax.swing.JButton();
        licencia = new javax.swing.JButton();
        contReserva = new javax.swing.JButton();
        regresarreserv = new javax.swing.JButton();
        edad_cliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        correo_cliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRES CORONAS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alquiler/de/Imagenes/corona (1).png"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre (s)");

        jLabel2.setText("Apellidos");

        nombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_clienteActionPerformed(evt);
            }
        });

        apellidos_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidos_clienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Edad");

        jLabel6.setText("Numero telefonico");

        telefono_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_clienteActionPerformed(evt);
            }
        });

        ine.setText("Adjuntar INE");
        ine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ineActionPerformed(evt);
            }
        });

        licencia.setText("Adjuntar licencia de conducir");
        licencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenciaActionPerformed(evt);
            }
        });

        contReserva.setBackground(new java.awt.Color(51, 0, 0));
        contReserva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contReserva.setForeground(new java.awt.Color(255, 255, 255));
        contReserva.setText("Continuar");
        contReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contReservaActionPerformed(evt);
            }
        });

        regresarreserv.setText("Regresar");
        regresarreserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarreservActionPerformed(evt);
            }
        });

        edad_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edad_clienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Correo Electronico");

        correo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo_clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(regresarreserv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(licencia)
                        .addGap(82, 82, 82)
                        .addComponent(contReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(correo_cliente)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(edad_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_cliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidos_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(telefono_cliente, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(358, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(regresarreserv)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apellidos_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edad_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(correo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licencia)
                    .addComponent(ine)
                    .addComponent(contReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_clienteActionPerformed
      // Obtener el texto del JTextField
    String nombre = nombre_cliente.getText();
    
    // Validar que el campo no esté vacío
    if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El campo 'Nombre' no puede estar vacío.");
        return;
    }
    
    // Conexión a la base de datos
    String sql = "INSERT INTO alquileres (nombre_cliente) VALUES (?)";
    try {
        conet = con1.conectar(); // Asegúrate de que Conexion tenga un método getConnection()
        java.sql.PreparedStatement pstmt = conet.prepareStatement(sql);
        pstmt.setString(1, nombre); // Establecer el nombre en la consulta
        
        int resultado = pstmt.executeUpdate(); // Ejecutar la consulta
        if (resultado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Nombre guardado exitosamente!");
            nombre_cliente.setText(""); // Limpiar el JTextField
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el nombre.");
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage());
    }
    
    // Navegar a la siguiente ventana
    Confirmacion a = new Confirmacion();
    a.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_nombre_clienteActionPerformed

    private void telefono_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_clienteActionPerformed

    private void ineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ineActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Selecciona el archivo del INE");
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos JPG", "jpg"));

    int returnValue = fileChooser.showOpenDialog(this);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        rutaINE = fileChooser.getSelectedFile().getAbsolutePath(); // Asignar la ruta seleccionada
        JOptionPane.showMessageDialog(this, "Archivo INE seleccionado: " + rutaINE);
    } else {
        JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo.");
    }
    }//GEN-LAST:event_ineActionPerformed

    

    private void licenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenciaActionPerformed
       JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Selecciona el archivo de la Licencia de Conducir");
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos JPG", "jpg"));

    int returnValue = fileChooser.showOpenDialog(this);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        rutaLicencia = fileChooser.getSelectedFile().getAbsolutePath(); // Asignar la ruta seleccionada
        JOptionPane.showMessageDialog(this, "Archivo Licencia seleccionado: " + rutaLicencia);
    } else {
        JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo.");
    }
    }//GEN-LAST:event_licenciaActionPerformed

    private void regresarreservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarreservActionPerformed
        tarjeta d = new tarjeta();
        d.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_regresarreservActionPerformed

    // Método para validar todos los campos
private boolean validarCampos() {
    // Validar que los campos no estén vacíos
    if (nombre_cliente.getText().trim().isEmpty() || 
        apellidos_cliente.getText().trim().isEmpty() ||
        edad_cliente.getText().trim().isEmpty() || 
        telefono_cliente.getText().trim().isEmpty() ||
        correo_cliente.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
        return false;
    }

    // Validar que nombre y apellidos contengan solo letras
    if (!nombre_cliente.getText().matches("^[a-zA-ZÁÉÍÓÚÑáéíóúñ\\s]+$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras y espacios.");
        return false;
    }
    if (!apellidos_cliente.getText().matches("^[a-zA-ZÁÉÍÓÚÑáéíóúñ\\s]+$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Los apellidos solo deben contener letras y espacios.");
        return false;
    }

    // Validar que la edad sea un número y esté en el rango permitido
    try {
        int edad = Integer.parseInt(edad_cliente.getText().trim());
        if (edad < 18 || edad > 100) {
            javax.swing.JOptionPane.showMessageDialog(this, "La edad debe estar entre 18 y 100 años.");
            return false;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "La edad debe ser un número válido.");
        return false;
    }

    // Validar que el teléfono tenga exactamente 10 dígitos
    if (!telefono_cliente.getText().matches("\\d{10}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El número telefónico debe tener exactamente 10 dígitos.");
        return false;
    }

    // Validar que el correo tenga un formato válido
    if (!correo_cliente.getText().matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El correo electrónico no tiene un formato válido.");
        return false;
    }

    return true;
}
    // Variables de instancia para almacenar las rutas seleccionadas
    private String rutaINE = null;
    private String rutaLicencia = null;

    private void contReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contReservaActionPerformed
        // Validar campos
    if (!validarCampos()) {
        return; // Detener si hay errores en la validación
    }

    // Validar que las rutas del INE y Licencia no estén vacías
    if (rutaINE == null || rutaINE.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona el archivo del INE antes de continuar.");
        return;
    }
    if (rutaLicencia == null || rutaLicencia.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona el archivo de la Licencia antes de continuar.");
        return;
    }

    // Obtener los valores de los JTextField
    String nombre = nombre_cliente.getText().trim();
    String apellidos = apellidos_cliente.getText().trim();
    int edad = Integer.parseInt(edad_cliente.getText().trim());
    String telefono = telefono_cliente.getText().trim();
    String correo = correo_cliente.getText().trim();

    // Código para guardar o actualizar los datos en la base
    String sql = "UPDATE alquileres SET nombre_cliente = ?, apellidos_cliente = ?, edad_cliente = ?, telefono_cliente = ?, correo_cliente = ?, ruta_ine = ?, ruta_licencia = ? WHERE id_alquiler = ?";

    try {
        conet = con1.conectar();
        PreparedStatement pstmt = conet.prepareStatement(sql);

        pstmt.setString(1, nombre);
        pstmt.setString(2, apellidos);
        pstmt.setInt(3, edad);
        pstmt.setString(4, telefono);
        pstmt.setString(5, correo);
        pstmt.setString(6, rutaINE); // Ruta del INE
        pstmt.setString(7, rutaLicencia); // Ruta de la Licencia
        pstmt.setInt(8, id_alquiler);

        int resultado = pstmt.executeUpdate();
        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "¡Datos actualizados exitosamente!");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar los datos.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage());
    }

    // Navegar a la siguiente ventana
    tarjeta a = new tarjeta();
    a.setVisible(true);
    this.dispose();
}

    // Métodos para asignar las rutas seleccionadas desde JFileChooser
// Método para limpiar los JTextField
    private void limpiarCampos() {
    nombre_cliente.setText("");
    apellidos_cliente.setText("");
    edad_cliente.setText("");
    telefono_cliente.setText("");
    correo_cliente.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_contReservaActionPerformed

    private void apellidos_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidos_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidos_clienteActionPerformed

    private void edad_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edad_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edad_clienteActionPerformed

    private void correo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reservar(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos_cliente;
    private javax.swing.JButton contReserva;
    private javax.swing.JTextField correo_cliente;
    private javax.swing.JTextField edad_cliente;
    private javax.swing.JButton ine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton licencia;
    private javax.swing.JTextField nombre_cliente;
    private javax.swing.JButton regresarreserv;
    private javax.swing.JTextField telefono_cliente;
    // End of variables declaration//GEN-END:variables
}
