/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alquiler.de.autos;
import java.sql.Connection;
import javax.swing.*; 
import javax.swing.event.ChangeEvent; 
import javax.swing.event.ChangeListener; 
import java.util.Date; 
import java.sql.SQLException;
import java.sql.PreparedStatement;
/**
 *
 * @author yc
 */
public class vistaR extends javax.swing.JFrame {
    Conexion con1 = new Conexion();
    Connection conet;
    /**
     * Creates new form login
     */
    public vistaR() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        continuarRecoleccion = new javax.swing.JButton();
        lugar_recoleccion = new javax.swing.JComboBox<>();
        lugar_devolucion = new javax.swing.JComboBox<>();
        fecha_inicio_recoleccion = new javax.swing.JTextField();
        fecha_fin_devolucion = new javax.swing.JTextField();
        hora_fin_devolucion = new javax.swing.JTextField();
        hora_inicio_recoleccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Devolución");

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRES CORONAS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alquiler/de/Imagenes/corona (1).png"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Recolección");

        continuarRecoleccion.setBackground(new java.awt.Color(51, 0, 0));
        continuarRecoleccion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        continuarRecoleccion.setForeground(new java.awt.Color(255, 255, 255));
        continuarRecoleccion.setText("Continuar");
        continuarRecoleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarRecoleccionActionPerformed(evt);
            }
        });

        lugar_recoleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿En que estado comienza el viaje?", "Oaxaca centro", "Puerto Escondido", "Istmo" }));
        lugar_recoleccion.setToolTipText("");
        lugar_recoleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar_recoleccionActionPerformed(evt);
            }
        });

        lugar_devolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Donde termina el viaje?", "Oaxaca", "Puerto escondido, oax", "Istmo" }));
        lugar_devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar_devolucionActionPerformed(evt);
            }
        });

        hora_inicio_recoleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_inicio_recoleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(continuarRecoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lugar_recoleccion, 0, 264, Short.MAX_VALUE)
                            .addComponent(lugar_devolucion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecha_inicio_recoleccion)
                            .addComponent(fecha_fin_devolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hora_fin_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hora_inicio_recoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lugar_recoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_inicio_recoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_inicio_recoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lugar_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_fin_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_fin_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(continuarRecoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lugar_recoleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar_recoleccionActionPerformed

    }//GEN-LAST:event_lugar_recoleccionActionPerformed

    private static int id_alquiler;
    
    private void continuarRecoleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarRecoleccionActionPerformed
         // Recuperar datos de los campos
    String lugarRec = lugar_recoleccion.getSelectedItem().toString();
    String lugarDev = lugar_devolucion.getSelectedItem().toString();
    String fechaInicio = fecha_inicio_recoleccion.getText();
    String fechaFin = fecha_fin_devolucion.getText();
    String horaInicio = hora_inicio_recoleccion.getText();
    String horaFin = hora_fin_devolucion.getText();

    // Validaciones
    if (lugarRec.equals("¿En que estado comienza el viaje?") || lugarDev.equals("¿Donde termina el viaje?")) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona un lugar válido.");
        return;
    }

    if (fechaInicio.isEmpty() || fechaFin.isEmpty() || horaInicio.isEmpty() || horaFin.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor llena todos los campos.");
        return;
    }

    try {
        // Validar formato de fecha
        java.sql.Date.valueOf(fechaInicio); // Formato esperado: YYYY-MM-DD
        java.sql.Date.valueOf(fechaFin);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa las fechas en el formato YYYY-MM-DD.");
        return;
    }

    try {
        // Validar formato de hora
        java.sql.Time.valueOf(horaInicio); // Formato esperado: HH:MM:SS
        java.sql.Time.valueOf(horaFin);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa las horas en el formato HH:MM:SS.");
        return;
    }

    // Crear el SQL de inserción
    String sql = "INSERT INTO alquileres (lugar_recoleccion, lugar_devolucion, fecha_inicio_recoleccion, fecha_fin_devolucion, hora_inicio_recoleccion, hora_fin_devolucion) VALUES (?, ?, ?, ?, ?, ?)";

    try {
        conet = con1.conectar(); 
        PreparedStatement pstmt = conet.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS); 
        
        pstmt.setString(1, lugarRec); // lugar de recolección
        pstmt.setString(2, lugarDev); // lugar de devolución
        pstmt.setDate(3, java.sql.Date.valueOf(fechaInicio)); // fecha de inicio
        pstmt.setDate(4, java.sql.Date.valueOf(fechaFin)); // fecha de fin
        pstmt.setTime(5, java.sql.Time.valueOf(horaInicio)); // hora de inicio
        pstmt.setTime(6, java.sql.Time.valueOf(horaFin)); // hora de fin

        // Ejecutar la inserción
        pstmt.executeUpdate();
        
        // Recuperar el id generado automáticamente
        java.sql.ResultSet rs = pstmt.getGeneratedKeys();
        if (rs.next()) {
            id_alquiler = rs.getInt(1);
            System.out.println("ID generado: " + id_alquiler); // Verifica si se muestra el ID correcto
        }

        // Mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Alquiler guardado exitosamente.");
        
        // Proceder a la siguiente ventana
        pasajeros n2 = new pasajeros(id_alquiler);
        n2.setVisible(true);
        this.dispose();
    } catch (SQLException e) {
        // Mostrar error en caso de que falle la inserción
        JOptionPane.showMessageDialog(this, "Error al guardar el alquiler: " + e.getMessage());
    }
        
        
    }//GEN-LAST:event_continuarRecoleccionActionPerformed

    private void lugar_devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar_devolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugar_devolucionActionPerformed

    private void hora_inicio_recoleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_inicio_recoleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_inicio_recoleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuarRecoleccion;
    private javax.swing.JTextField fecha_fin_devolucion;
    private javax.swing.JTextField fecha_inicio_recoleccion;
    private javax.swing.JTextField hora_fin_devolucion;
    private javax.swing.JTextField hora_inicio_recoleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> lugar_devolucion;
    private javax.swing.JComboBox<String> lugar_recoleccion;
    // End of variables declaration//GEN-END:variables
}
